"""
app_theme.py — push the active qtile colour theme out to other apps.

The qtile bar palettes (modules/screens.py) are the single source of truth for a
theme. functions.apply_theme() calls apply_app_themes(palette) so switching theme
also retints the rest of the desktop:

  • Alacritty -> ~/.config/alacritty/colors.toml        (live_config_reload)
  • dunst     -> ~/.config/dunst/dunstrc.d/01-theme.conf + `dunstctl reload`
  • calcurse  -> ~/.config/calcurse/conf appearance.theme (applies next launch;
                 the bar's calendar scratchpad relaunches calcurse every time)

Design choice: only background / foreground / cursor / accent follow the theme.
The 16 ANSI colours stay a fixed, functional set so terminal output (ls, vim,
git, syntax highlighting) keeps its meaning instead of turning monochrome.
"""
import colorsys
import os
import subprocess


# Functional ANSI palette, identical across every theme (semantic colours stay
# readable). Only black/white are swapped for theme tones (see theme_alacritty).
_ANSI = {
    "normal": {"red": "#E06B74", "green": "#98C379", "yellow": "#E5C07A",
               "blue": "#62AEEF", "magenta": "#C778DD", "cyan": "#55B6C2"},
    "bright": {"red": "#EA757E", "green": "#A2CD83", "yellow": "#EFCA84",
               "blue": "#6CB8F9", "magenta": "#D282E7", "cyan": "#5FC0CC"},
}


def _h(p):
    return os.path.expanduser(p)


def _lighten(hexc, f):
    r, g, b = (int(hexc.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4))
    return "#%02X%02X%02X" % tuple(min(255, int(c + (255 - c) * f)) for c in (r, g, b))


def _mix(a, b, t):
    ca = [int(a.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4)]
    cb = [int(b.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4)]
    return "#%02X%02X%02X" % tuple(int(ca[i] + (cb[i] - ca[i]) * t) for i in range(3))


def _lum(hexc):
    r, g, b = (int(hexc.lstrip("#")[i:i + 2], 16) / 255 for i in (0, 2, 4))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def _on(bg, dark, light):
    """Pick the readable foreground (dark or light) for a background colour."""
    return dark if _lum(bg) > 0.55 else light


# ── Alacritty ─────────────────────────────────────────────────────────────────
def theme_alacritty(pal):
    n, b = _ANSI["normal"], _ANSI["bright"]
    txt = f'''# Generated by qtile apply_theme — overwritten on every theme switch.
[colors.primary]
background = "{pal['bg']}"
foreground = "{pal['fg_light']}"

[colors.cursor]
cursor = "{pal['accent']}"
text = "{pal['bg']}"

[colors.selection]
background = "{pal['bg2']}"
text = "{pal['fg_light']}"

[colors.normal]
black = "{pal['bg2']}"
red = "{n['red']}"
green = "{n['green']}"
yellow = "{n['yellow']}"
blue = "{n['blue']}"
magenta = "{n['magenta']}"
cyan = "{n['cyan']}"
white = "{pal['fg']}"

[colors.bright]
black = "{_lighten(pal['bg2'], 0.25)}"
red = "{b['red']}"
green = "{b['green']}"
yellow = "{b['yellow']}"
blue = "{b['blue']}"
magenta = "{b['magenta']}"
cyan = "{b['cyan']}"
white = "{pal['fg_light']}"
'''
    with open(_h("~/.config/alacritty/colors.toml"), "w") as f:
        f.write(txt)
    # Alacritty's live reload watches the PRIMARY config file; changing an
    # imported file (colors.toml) alone does not reliably fire it for windows
    # that are already open. Bump the primary file's mtime so every running
    # terminal re-reads its imports and recolours immediately.
    try:
        os.utime(_h("~/.config/alacritty/alacritty.toml"), None)
    except OSError:
        pass


# ── dunst ─────────────────────────────────────────────────────────────────────
def theme_dunst(pal):
    conf = f'''# Generated by qtile apply_theme — overwritten on every theme switch.
[global]
    background = "{pal['bg2']}"
    foreground = "{pal['fg_light']}"
    frame_color = "{pal['accent']}"
    frame_width = 2
    highlight = "{pal['accent']}"
    separator_color = frame

[urgency_low]
    background = "{pal['bg2']}"
    foreground = "{pal['fg']}"
    frame_color = "{pal['accent']}"

[urgency_normal]
    background = "{pal['bg2']}"
    foreground = "{pal['fg_light']}"
    frame_color = "{pal['accent']}"

[urgency_critical]
    background = "{pal['bg2']}"
    foreground = "{pal['fg_light']}"
    frame_color = "{pal['ai']}"
'''
    d = _h("~/.config/dunst/dunstrc.d")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, "01-theme.conf"), "w") as f:
        f.write(conf)
    try:
        subprocess.Popen(["dunstctl", "reload"])
    except FileNotFoundError:
        pass


# ── calcurse ──────────────────────────────────────────────────────────────────
# calcurse only knows the 8 named ncurses colours; pick the nearest by hue.
_NCURSES = [(0, "red"), (45, "yellow"), (90, "green"), (175, "cyan"),
            (235, "blue"), (300, "magenta"), (360, "red")]


def _nearest_ncurses(hexc):
    r, g, b = (int(hexc.lstrip("#")[i:i + 2], 16) / 255 for i in (0, 2, 4))
    hh, _ll, ss = colorsys.rgb_to_hls(r, g, b)
    if ss < 0.12:
        return "white"
    deg = hh * 360
    return min(_NCURSES, key=lambda nd: abs(deg - nd[0]))[1]


def theme_calcurse(pal):
    conf = _h("~/.config/calcurse/conf")
    if not os.path.exists(conf):
        return
    color = _nearest_ncurses(pal["accent"])
    out, found = [], False
    for line in open(conf).read().splitlines():
        if line.startswith("appearance.theme="):
            out.append(f"appearance.theme={color} on default")
            found = True
        else:
            out.append(line)
    if not found:
        out.append(f"appearance.theme={color} on default")
    with open(conf, "w") as f:
        f.write("\n".join(out) + "\n")


# ── rofi ──────────────────────────────────────────────────────────────────────
def _rgba(hexc, a=100):
    r, g, b = (int(hexc.lstrip("#")[i:i + 2], 16) for i in (0, 2, 4))
    return f"rgba ( {r}, {g}, {b}, {a} % )"


def theme_rofi(pal):
    """Write ~/.config/rofi/custom_theme.rasi (imported by config.rasi).

    rofi re-reads its theme on every launch, so the next menu is themed with no
    daemon to reload. Only the colour variables change; the layout in
    config.rasi stays untouched.
    """
    txt = f'''/* Generated by qtile apply_theme — overwritten on every theme switch. */
* {{
    selected-normal-foreground:  {_rgba(pal['fg_light'])};
    foreground:                  {_rgba(pal['fg_light'])};
    normal-foreground:           @foreground;
    alternate-normal-background: {_rgba(pal['bg'], 0)};
    red:                         rgba ( 220, 50, 47, 100 % );
    selected-urgent-foreground:  {_rgba(pal['bg'])};
    blue:                        {_rgba(pal['accent'])};
    urgent-foreground:           {_rgba(pal['ai'])};
    alternate-urgent-background: {_rgba(pal['bg2'], 40)};
    active-foreground:           {_rgba(pal['primary'])};
    lightbg:                     {_rgba(pal['fg_light'])};
    selected-active-foreground:  {_rgba(pal['fg_light'])};
    alternate-active-background: {_rgba(pal['accent'], 17)};
    background:                  {_rgba(pal['bg'], 92)};
    alternate-normal-foreground: @foreground;
    normal-background:           {_rgba(pal['bg'], 0)};
    lightfg:                     {_rgba(pal['fg'])};
    selected-normal-background:  {_rgba(pal['accent'])};
    border-color:                {_rgba(pal['accent'])};
    spacing:                     20;
    separatorcolor:              {_rgba(pal['accent'], 60)};
    urgent-background:           {_rgba(pal['bg2'], 40)};
    selected-urgent-background:  {_rgba(pal['ai'])};
    alternate-urgent-foreground: @urgent-foreground;
    background-color:            rgba ( 0, 0, 0, 0 % );
    alternate-active-foreground: @active-foreground;
    active-background:           {_rgba(pal['accent'], 17)};
    selected-active-background:  {_rgba(pal['accent'])};
}}
'''
    with open(_h("~/.config/rofi/custom_theme.rasi"), "w") as f:
        f.write(txt)


# ── pywal sequences ───────────────────────────────────────────────────────────
def theme_wal_sequences(pal):
    """Regenerate ~/.cache/wal/sequences from the theme and push it to open shells.

    ~/.zshrc runs `cat ~/.cache/wal/sequences` on every shell start, which emits
    OSC escape codes that OVERRIDE Alacritty's colors.toml with whatever pywal
    last generated — a stale green palette. That is why a terminal opened with a
    zsh shell ignored the theme. We rewrite that file from the active palette
    (matching colors.toml) and also write it to every open /dev/pts so running
    terminals recolour immediately, not just new ones.
    """
    n, b = _ANSI["normal"], _ANSI["bright"]
    palette = [
        pal["bg"], n["red"], n["green"], n["yellow"], n["blue"],
        n["magenta"], n["cyan"], pal["fg"],
        _lighten(pal["bg2"], 0.25), b["red"], b["green"], b["yellow"],
        b["blue"], b["magenta"], b["cyan"], pal["fg_light"],
    ]
    E = "\033"
    seq = "".join(f"{E}]4;{i};{c}{E}\\" for i, c in enumerate(palette))
    seq += f"{E}]10;{pal['fg_light']}{E}\\"   # foreground
    seq += f"{E}]11;{pal['bg']}{E}\\"          # background
    seq += f"{E}]12;{pal['accent']}{E}\\"      # cursor
    seq += f"{E}]13;{pal['accent']}{E}\\"      # cursor (pointer)
    seq += f"{E}]17;{pal['bg2']}{E}\\"         # selection background
    seq += f"{E}]19;{pal['fg_light']}{E}\\"    # selection foreground
    seq += f"{E}]4;232;{pal['bg']}{E}\\"
    seq += f"{E}]4;256;{pal['fg_light']}{E}\\"
    seq += f"{E}]708;{pal['bg']}{E}\\"         # border
    cache = _h("~/.cache/wal")
    try:
        os.makedirs(cache, exist_ok=True)
        with open(os.path.join(cache, "sequences"), "w") as f:
            f.write(seq)
    except OSError:
        pass
    import glob
    for pts in glob.glob("/dev/pts/[0-9]*"):
        try:
            with open(pts, "w") as t:
                t.write(seq)
        except OSError:
            pass


# ── starship prompt ───────────────────────────────────────────────────────────
# The shipped starship.toml hardcodes the green/sage palette (powerline segment
# backgrounds, the ~ "house" in [directory], git/lang accents, the username fg).
# We keep that file as the canonical TEMPLATE and regenerate ~/.config/starship.toml
# from it, remapping each hardcoded colour to the active theme. starship re-reads
# its config on every prompt, so the next prompt is themed — no reload needed.
_STARSHIP_TPL = "~/.config/qtile/templates/starship.toml"


def theme_starship(pal):
    tpl, live = _h(_STARSHIP_TPL), _h("~/.config/starship.toml")
    if not os.path.exists(tpl):
        return
    s = open(tpl).read()
    g = [_mix(pal["bg"], pal["bg2"], t) for t in (0.30, 0.50, 0.75, 1.0)]
    repl = {
        "#141616": g[0], "#181A1A": g[1], "#1C1E1E": g[2], "#202222": g[3],
        "#607767": pal["fg"],         # directory — the green ~ house
        "#a6e3a1": pal["accent"],     # git branch / status
        "#cba6f7": pal["primary"],    # language version modules
        "#B2BEBC": pal["fg_light"], "#b2bebc": pal["fg_light"],  # username
    }
    for old, new in repl.items():
        s = s.replace(old, new)
    with open(live, "w") as f:
        f.write(s)


# ── GTK (GTK3 widgets + GTK2 / GTK4 legacy) ────────────────────────────────────
# A custom "Cozy" theme lives in ~/.local/share/themes/Cozy/. Its GTK3 widget
# rules are fixed and @import a colors.css that we regenerate here from the
# palette; GTK2/GTK4 can't @import so their @@TOKEN@@ templates are
# string-substituted. Running GTK3 apps recolour live via a settings.ini
# theme-name toggle — but only once GTK_THEME is unset in the session (it is
# removed from ~/.xprofile; full effect after the next re-login).
_COZY = "~/.local/share/themes/Cozy"


def theme_gtk(pal):
    bg, bg2, _fg, fgl, acc, pri = (pal[k] for k in
                                   ("bg", "bg2", "fg", "fg_light", "accent", "primary"))
    base = _mix(bg, bg2, 0.35)
    sel_fg = _on(acc, bg, fgl)              # readable text on the accent fill
    border = _mix(bg2, fgl, 0.16)
    insens_fg = _mix(bg, fgl, 0.6)
    colors = {
        "theme_bg_color": bg, "theme_fg_color": fgl, "theme_bg2_color": bg2,
        "theme_base_color": base, "theme_text_color": fgl,
        # A traditional GtkMenu (Thunar's menubar) draws ENABLED shortcut text
        # with theme_selected_fg_color, NOT the menuitem colour — so it must read
        # clearly on the DARK menu. Use the light fg (like the green theme, where
        # the accent is dark so this resolves light and the shortcuts look crisp).
        # The HIGHLIGHTED row's text/shortcut still goes dark via menuitem:hover
        # (accent_text_color), and every real selection uses accent_text_color too
        # (explicit rules + scoped list/combo catch-all), so the orange highlight
        # keeps dark, high-contrast text.
        "theme_selected_bg_color": acc, "theme_selected_fg_color": fgl,
        "accent_text_color": sel_fg,
        "accent_color": acc, "accent_fg_color": sel_fg,
        "theme_hover_color": _mix(bg2, fgl, 0.10), "borders_color": border,
        "insensitive_bg_color": bg, "insensitive_fg_color": insens_fg,
        "warning_color": "#E5C07A", "error_color": "#E06B74",
        "success_color": "#98C379",
        "tooltip_bg_color": bg2, "tooltip_fg_color": fgl, "primary_color": pri,
    }
    cozy = _h(_COZY)
    tpl = _h("~/.config/qtile/templates")
    # Self-install: (re)build the Cozy theme dir from the committed templates.
    try:
        import shutil
        for sub in ("gtk-3.0", "gtk-2.0", "gtk-4.0"):
            os.makedirs(os.path.join(cozy, sub), exist_ok=True)
        shutil.copyfile(os.path.join(tpl, "cozy-index.theme"),
                        os.path.join(cozy, "index.theme"))
        with open(os.path.join(cozy, "gtk-3.0", "gtk.css"), "w") as f:
            f.write('@import url("colors.css");\n\n'
                    + open(os.path.join(tpl, "cozy-gtk3.css")).read())
    except OSError:
        return                              # templates missing
    body = "/* regenerated by qtile apply_theme (theme_gtk) */\n"
    body += "".join(f"@define-color {k} {v};\n" for k, v in colors.items())
    with open(os.path.join(cozy, "gtk-3.0", "colors.css"), "w") as f:
        f.write(body)

    # GTK2 + GTK4 templates: substitute the @@TOKEN@@ placeholders.
    tok = {
        "@@BG@@": bg, "@@BG2@@": bg2, "@@FG@@": fgl, "@@FG_LIGHT@@": fgl,
        "@@ACCENT@@": acc, "@@BASE@@": base, "@@TEXT@@": fgl,
        "@@SEL_BG@@": acc, "@@SEL_FG@@": sel_fg, "@@BORDER@@": border,
        "@@INSENS_FG@@": insens_fg, "@@PRIMARY@@": pri, "@@DESTRUCTIVE@@": "#E06B74",
    }

    def _subst(src, dst):
        try:
            s = open(src).read()
            for k, v in tok.items():
                s = s.replace(k, v)
            with open(dst, "w") as f:
                f.write(s)
        except OSError:
            pass

    _subst(os.path.join(tpl, "cozy-gtk2.gtkrc"), os.path.join(cozy, "gtk-2.0", "gtkrc"))
    g4 = os.path.join(cozy, "gtk-4.0", "gtk.css")
    _subst(os.path.join(tpl, "cozy-gtk4.css"), g4)
    try:                                    # libadwaita reads ~/.config/gtk-4.0/gtk.css
        import shutil
        os.makedirs(_h("~/.config/gtk-4.0"), exist_ok=True)
        shutil.copyfile(g4, _h("~/.config/gtk-4.0/gtk.css"))
    except OSError:
        pass

    # Point GTK at Cozy + live-reload running GTK3 apps. GTK3 re-applies CSS only
    # when the gtk-theme-name VALUE changes, so flip to a throwaway name then back
    # to Cozy. Backgrounded so the 0.35s settle never blocks the qtile loop.
    ini = _h("~/.config/gtk-3.0/settings.ini")
    icon = ("Papirus-Dark" if os.path.isdir(_h("~/.local/share/icons/Papirus-Dark"))
            else "Zafiro-Icons-Light")
    tail = f'gtk-icon-theme-name={icon}\\ngtk-application-prefer-dark-theme=1\\n'
    sh = (f'printf "[Settings]\\ngtk-theme-name=Adwaita\\n{tail}" > "{ini}"; sleep 0.35; '
          f'printf "[Settings]\\ngtk-theme-name=Cozy\\n{tail}" > "{ini}"')
    subprocess.Popen(["sh", "-c", sh])
    try:
        subprocess.Popen(["gsettings", "set",
                          "org.gnome.desktop.interface", "gtk-theme", "Cozy"])
    except FileNotFoundError:
        pass


# ── icons (Papirus, folder colour follows the palette) ─────────────────────────
# Papirus must be installed USER-LOCAL (~/.local/share/icons) so papirus-folders
# can recolour its folders without root — run scripts/icons-setup.sh once. The
# theme then picks the Papirus folder colour nearest the palette accent. Silently
# skipped until Papirus is present, so nothing breaks before setup.
_PAPIRUS_HUES = [(15, "red"), (22, "deeporange"), (40, "orange"), (55, "yellow"),
                 (110, "green"), (170, "teal"), (195, "cyan"), (220, "blue"),
                 (250, "indigo"), (282, "violet"), (312, "magenta"), (340, "pink"),
                 (360, "red")]


def _papirus_color(hexc):
    import colorsys
    r, g, b = (int(hexc.lstrip("#")[i:i + 2], 16) / 255 for i in (0, 2, 4))
    hh, _l, ss = colorsys.rgb_to_hls(r, g, b)
    if ss < 0.15:
        return "grey"
    deg = hh * 360
    return min(_PAPIRUS_HUES, key=lambda x: abs(deg - x[0]))[1]


def theme_icons(pal):
    if not os.path.isdir(_h("~/.local/share/icons/Papirus-Dark")):
        return                              # not installed (run scripts/icons-setup.sh)
    pf = _h("~/.config/qtile/scripts/papirus-folders")
    if os.path.exists(pf):
        subprocess.Popen(["bash", pf, "-C", _papirus_color(pal["accent"]),
                          "-t", "Papirus-Dark", "-u"])
    try:
        subprocess.Popen(["gsettings", "set",
                          "org.gnome.desktop.interface", "icon-theme", "Papirus-Dark"])
    except FileNotFoundError:
        pass


# ── orchestrator ──────────────────────────────────────────────────────────────
def apply_app_themes(pal):
    """Push palette dict `pal` to every themed app (terminal, notifications,
    calendar, launcher, prompt, GTK apps, icons).

    Each channel is isolated so a failure in one app never breaks the others or
    the qtile bar swap that called us.
    """
    for fn in (theme_alacritty, theme_dunst, theme_calcurse, theme_rofi,
               theme_wal_sequences, theme_starship, theme_gtk, theme_icons):
        try:
            fn(pal)
        except Exception:
            pass
