class COLORS:
    PRIMARY_LIGHT = "#fb958b"
    PRIMARY = "#d3c2aa"
    PRIMARY_DARK = "#973232"
    PRIMARY_MUTED = "#2c2f30ff"
    PRIMARY_MUTED = "#131c26"
    FOREGROUND = "#ffffff"
    INACTIVE = PRIMARY_MUTED


class BASE:
    # PRIMARY =  "#bd00e7ff",
    PRIMARY = COLORS.PRIMARY
    SECONDARY = ("",)
    BACKGROUND = '#282738'
    BACKGROUND2 = '#353446'

    FOREGROUND = '#E5B9C6'
    BLOCK_TEXT_HIGHLIGHT = "#CFB3E5"
    HIGHLIGHT = '#4B427E'




class WINDOW:
    FOCUSED = BASE.PRIMARY
    UNFOCUSED = COLORS.PRIMARY_MUTED
