class COLORS:
    PRIMARY_LIGHT = "#fb958b"
    PRIMARY = "#d3c2aa"
    PRIMARY_DARK = "#973232"
    PRIMARY_MUTED = "#131c26"
    FOREGROUND = "#ffffff"
    INACTIVE = PRIMARY_MUTED


class BASE:
    # PRIMARY =  "#bd00e7ff",
    PRIMARY = COLORS.PRIMARY
    SECONDARY = ("",)
    BACKGROUND = '#0F1212'
    BACKGROUND2 = '#202222'

    FOREGROUND = '#607767'
    BLOCK_TEXT_HIGHLIGHT = "#B2BEBC"
    HIGHLIGHT = '#202222'




class WINDOW:
    FOCUSED = BASE.PRIMARY
    UNFOCUSED = COLORS.PRIMARY_MUTED
