Section "InputClass"
    Identifier "libinput touchpad catchall"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "on"
    Option "TappingButtonMap" "lrm"  # Left = tap, Right = 2-finger tap, Middle = 3-finger tap
    Option "NaturalScrolling" "false"  # Optional: for traditional scrolling behavior
    Option "DisableWhileTyping" "true"  # Optional: Disable touchpad when typing
    Option "ClickMethod" "clickfinger"  # Enable tap as click method
EndSection