#!/usr/bin/env bash
# =============================================================================
# sddm-sync.sh — recolour the 'cozy' SDDM login screen to match a cozy-dot-files
# theme (the same palettes in ~/.config/qtile/themes.json that the rofi theme
# picker uses), and copy that theme's wallpaper as the login background.
#
#   sudo bash scripts/sddm-sync.sh            # follow the CURRENT qtile theme
#   sudo bash scripts/sddm-sync.sh negro      # follow a specific theme by name
#
# The login screen is owned by root (/usr/share/sddm), so this needs sudo. It is
# NOT run on every in-session theme switch on purpose — you don't see the login
# screen while changing themes anyway. Run it whenever you want the two to match.
#
# Palette → greeter mapping:
#   bg=bg · fg=fg_light · fgDim=fg · accent=primary · field=bg2 · border=bg2
# =============================================================================
set -euo pipefail
[ "$(id -u)" -eq 0 ] || { echo "Run as root:  sudo bash $0 [theme]"; exit 1; }

DEST="/usr/share/sddm/themes/cozy"
[ -f "$DEST/Main.qml" ] || { echo "Theme not deployed yet. Run scripts/sddm-deploy.sh first."; exit 1; }

REAL_USER="${SUDO_USER:-$(logname 2>/dev/null || true)}"
[ -n "${REAL_USER:-}" ] || { echo "Could not determine your user; run via sudo, not as root."; exit 1; }
HOME_DIR="$(getent passwd "$REAL_USER" | cut -d: -f6)"
JSON="$HOME_DIR/.config/qtile/themes.json"
WALLS="$HOME_DIR/.config/qtile/wallpapers"
NAME="${1:-$(cat "$HOME_DIR/.config/qtile/.current_theme" 2>/dev/null || true)}"
[ -n "${NAME:-}" ] || { echo "No theme name given and no ~/.config/qtile/.current_theme found."; exit 1; }
[ -f "$JSON" ] || { echo "themes.json not found at $JSON"; exit 1; }

# Pull the palette + write theme.conf. Python keeps the JSON parsing robust.
python3 - "$JSON" "$NAME" "$DEST/theme.conf" <<'PY'
import json, sys
json_path, name, conf_path = sys.argv[1], sys.argv[2], sys.argv[3]
data = json.load(open(json_path))
if name not in data:
    sys.exit(f"Theme '{name}' is not registered in themes.json (have: {', '.join(data)}).")
p = data[name]
def g(k, fallback): return p.get(k, fallback)
conf = f"""[General]
# Auto-generated by sddm-sync.sh from theme '{name}'. Edit themes.json instead.
background=backgrounds/bg
bg={g('bg','#0E0F11')}
fg={g('fg_light','#E8EBEA')}
fgDim={g('fg','#828B89')}
accent={g('primary','#A7BCB1')}
field={g('bg2','#15181A')}
border={g('bg2','#2A2E30')}
"""
open(conf_path, "w").write(conf)
print(f"theme.conf written for '{name}':")
print(f"  bg {g('bg','?')}  fg {g('fg_light','?')}  accent {g('primary','?')}  field {g('bg2','?')}")
PY

# Copy the theme's wallpaper as the login background, if one exists.
bg_set=""
for ext in png jpg jpeg; do
    src="$WALLS/$NAME.$ext"
    if [ -f "$src" ]; then
        rm -f "$DEST/backgrounds/bg" "$DEST/backgrounds/bg".*
        cp "$src" "$DEST/backgrounds/bg"
        bg_set="$src"
        break
    fi
done
if [ -n "$bg_set" ]; then
    echo "  background ← $bg_set"
else
    # No dedicated wallpaper: fall back to a solid colour (the theme bg).
    sed -i 's#^background=.*#background=#' "$DEST/theme.conf"
    echo "  (no wallpaper for '$NAME' — using a solid background)"
fi

echo "Done. The login screen now matches '$NAME' on your next logout / reboot."
echo "Preview:  sddm-greeter-qt6 --test-mode --theme $DEST"
